# Generated by Django 5.1.3 on 2024-11-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
